### ISSUE TITLE
CSS s fonty z CDN

### ISSUE THREAD

**Issue by davidulus** [skaut/skaut-font#2]
Co přidat po vzoru Google fonts na CDN .css soubor s definicemi písem?

**Comment by LucoLoss** [comment]
Hotovo, doufám. Zároveň jsem přestyloval headery, aby nebyl každý SKAUT Boldem, nevypadá to pak úplně vábně.
Viz [CDN](http://cdn.skauting.cz/), resp. [vlastní soubor](https://cdn.skauting.cz/fonts/fonts.css).

**Comment by davidulus** [comment]
@LucoLoss @kalich5 
Díky. V tom samotném .css soboru by měla být jen deklarace písma bez dalšího stylování. Viz např. https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,700,700i
Ty styly pro body, h1, .bold, ... by tam být neměly.

**Comment by davidulus** [comment]
@LucoLoss @kalich5

**Comment by kalich5** [comment]
Přikládám upravený soubor s fonty. Je ale potřeba, aby ho @LucoLoss nahrál na web.

**Comment by kalich5** [comment]
[fonts.zip](https://github.com/skaut/skaut-font/files/1840785/fonts.zip)

**Comment by LucoLoss** [comment]
Pardon za prodlevu, vše by mělo být OK. Díky!

**Comment by kalich5** [comment]
Super, koukám na to. :-) Teď to půjde integrovat.
