### ISSUE TITLE
 Ensure text remains visible during webfont load 

### ISSUE THREAD

**Issue by jiriks74** [skaut/skaut-font#20]
Při testování rychlosti stránek dostávám následující chybu:
` Ensure text remains visible during webfont load `

Existuje plugin na řešení tohoto problému, avšak funguje pouze na google fonty. Dá se toto nějak vyřešit se skautskými fonty?

**Comment by jiriks74** [comment]
Je potřeba zařídit `font-display: swap;` avšak nejsem schopný toto nastavit bez přímé modifikace souborů pluginu nebo wordpressu, což ani jedno nechci dělat

**Comment by kalich5** [comment]
Udělej "Pull requests", my se na to podíváme a když to bude OK plugin upravíme.

**Comment by jiriks74** [comment]
Rád bych, jenže se zatím v PHP moc nevyznám. Rád se do toho pustím, jak budu mít chvíli času, ale bohužel to nestihnu teď. Šlo mi jen o to, jestli víte co s tím a jestli je to rychlý fix. Pokud ne, rád se do toho po maturitě pustím
