### ISSUE TITLE
Nefunguje nastavení

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-font#3]
@davidulus Objevil jsem chybu v nastavení.

**Popis webu:** Ať nastavím cokoliv pořád je tam to co je nastavení u **Nadpisů**

A pro delší popisy je lepší normální písmo, místo toho Skaut BOLD

**Comment by davidulus** [comment]
Zkus to s posledním commitem. Na jaké šabloně to zlobí? Já to testuji na twentyeleven - tam se to chová korektně.
"A pro delší popisy je lepší normální písmo, místo toho Skaut BOLD" - s tím mám dělat co? :-)

**Comment by kalich5** [comment]
Zkoušel jsem to na dsw-oddil šabloně na webu https://dobryweb.skauting.cz/

_"A pro delší popisy je lepší normální písmo, místo toho Skaut BOLD" - s tím mám dělat co? :-)_ - tohle bylo jen doplnění, nic víc :-)

**Comment by kalich5** [comment]
Tak to zkouším i jinde a v pohodě, takže to bude chyba té naší šablony. A ta by v další verzi měla mít to písmo v sobě, takže ten plugin by neměl být potřeba.

A ještě dotaz, co znamená v menu to "Neměnit"?

**Comment by davidulus** [comment]
Neměnit = výchozí. Pro případ, že by chtěl někdo plugin použít třeba jen na nadpisy a ne na běžné písmo.
