### ISSUE TITLE
404 u opentype formátů

### ISSUE THREAD

**Issue by davidulus** [skaut/skaut-font#5]
U opentype formátů (.otf) to hlásí 404:
https://cdn.skauting.cz/fonts/TheMix_LT_400.otf
https://cdn.skauting.cz/fonts/TheMix_LT_700.otf
...

**Comment by davidulus** [comment]
@LucoLoss @kalich5

**Comment by kalich5** [comment]
Tohle já bohužel nedokážu nijak zkontrolovat ani opravit. K tomu má přístup pouze @LucoLoss

**Comment by LucoLoss** [comment]
Opraveno.

**Comment by kalich5** [comment]
super :-)
